attach(data2)
head(data2)
str(data2)
summary(data2)
cor(data2)
pairs(data2)
v <- lm(Salario ~ Experiencia + Sexo, data = data2)
summary(v)
lm(formula = Salario ~ Experiencia + Sexo, data = data2)
v <- update(v,.~.+Experiencia:Sexo)
plot(v)
summary(v)
lm(formula = Salario ~ Experiencia + Sexo + Experiencia:Sexo, data = data2)